### ISSUE TITLE
Image resizing

### ISSUE THREAD

**Issue by polsvoice** [svbergerem/markdown-it-sanitizer#2]
I was recently talking with a Diaspora user who was frustrated because they could no longer use the `<img>` tag in posts and, as a result, could no longer resize images. I found [this StackOverflow thread](http://stackoverflow.com/questions/14675913/how-to-change-image-size-markdown) which mentioned a method used in some Markdown implementations that allows image resizing.

For example, to display an image at 300px wide x 450px high:

`
![](http://www.example.com/myImage.png =300x450)
`

What are your thoughts on implementing something like this?

**Comment by svbergerem** [comment]
I guess you are asking me to allow `height` and `width` attributes for `img` tags. The idea of `markdown-it-sanitizer` is to allow html code for things that you could also describe using markdown. Since the [commonmark spec](http://spec.commonmark.org/0.19/#images) doesn't allow height and width attributes for images, I won't allow them for `img` tags. Feel free to reopen when the commonmark spec allows those attributes.
