### ISSUE TITLE
Whitelist <i> tags

### ISSUE THREAD

**Issue by tobloef** [svbergerem/markdown-it-sanitizer#5]
When writing Markdown, it can be useful to be able to include icons using `<i>` tags, whether it's using FontAwesome or some other library.  So unless there's some security concern I don't know about, I would like to propose adding the `<i>` tag to the list of allowed tags.

**Edit:** Only just noticed that the `<i>` tags got picked up by GFM and converted the text to italic. I added backticks to prevent this.

**Comment by svbergerem** [comment]
As stated [here](https://github.com/svbergerem/markdown-it-sanitizer/issues/2#issuecomment-101393256)

> The idea of `markdown-it-sanitizer` is to allow html code for things that you could also describe using markdown.

I do however recognize that there are other applications for this library than my own and because of this issue I'm currently thinking about adding settings to change the accepted tags and attributes.

**Comment by tobloef** [comment]
I think that would be great feature to add. Even just loading a list of allowed tags from the config object, or use the default if the object doesn't contain the appropriate property , would probably work fine, right?
